name: Build and Package ROS Install Folder

on:
  push:
    branches:
      - master  # Change this to your default branch
  pull_request:
    branches:
      - master  # Change this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Restore build cache
      id: cache-build
      uses: actions/cache@v3
      with:
        path: build
        key: ${{ runner.os }}-build-${{ hashFiles('**/src/**') }}
        restore-keys: |
          ${{ runner.os }}-build-

    - name: Build Docker image
      run: docker build --target builder --tag ros-build -f Dockerfile_humble_22_04 .


    - name: Run Docker container to build ROS packages
      run: docker run --rm -v ${{ github.workspace }}:/work -w /work ros-build bash /work/build_ros2.sh

    - name: Zip the install folder
      run: zip -r ros_install.zip install

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: latest-build
        release_name: Latest Build
        draft: false
        prerelease: false
        generate_release_notes: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ros_install.zip
        asset_name: ros_install.zip
        asset_content_type: application/zip

    - name: Save build cache
      if: steps.cache-build.outputs.cache-hit != 'true'
      uses: actions/cache@v3
      with:
        path: build
        key: ${{ runner.os }}-build-${{ hashFiles('**/src/**') }}
